version: "3"

services:
  mongo:
    image: mongo:3.6
    container_name: mongo
    # restart: always
    ports:
        - 27017:27017
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    # restart: always
    ports:
      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  demo-service:
    image: demo-mongodb-java
    container_name: test-mongo
    build:
      context: .
    environment:
        SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/test_db
    ports:
      - 8088:8080
    depends_on:
      - mongo
